#!/usr/bin/env bash
#
# Posts a one-line message to the ops Slack channel via the incoming webhook
# (repo secret SLACK_OPS_WEBHOOK_URL). Used by .github/workflows/notify-deploy.yml
# to report what GitHub Pages did with a push to main — the Pages workflow is
# generated by GitHub and cannot be edited, so the reporting lives beside it
# rather than inside it.
#
# Same script, same secret name and same channel as oryjin-tech/core, so a
# website deploy and a core deploy read as one stream of ops events.
#
#   SLACK_OPS_WEBHOOK_URL=... ./scripts/notify-slack.sh "deploy failed: <url>"
#
# Never fails the calling job: a broken webhook must not turn a green run red,
# and on a failing run the red check + GitHub email still exist as fallback.
# No jq/node dependency — this repo has no toolchain to set up.
set -euo pipefail

MESSAGE="${1:?usage: $0 <message>}"

if [ -z "${SLACK_OPS_WEBHOOK_URL:-}" ]; then
	echo "::warning::SLACK_OPS_WEBHOOK_URL is not set — skipping Slack notification: $MESSAGE"
	exit 0
fi

# Minimal JSON string escaping (backslash, quote, newline) — enough for the
# workflow-authored messages this script is given.
escaped=${MESSAGE//\\/\\\\}
escaped=${escaped//\"/\\\"}
escaped=${escaped//$'\n'/\\n}

if ! curl -sS --max-time 10 -X POST -H 'Content-Type: application/json' \
	-d "{\"text\":\"$escaped\"}" "$SLACK_OPS_WEBHOOK_URL" > /dev/null; then
	echo "::warning::Slack notification failed to send: $MESSAGE"
fi
